import Foundation

enum MockPosts {
    static func make() -> [KiezioPost] {
        let now = Date()
        return [
            KiezioPost(id: UUID(), authorID: "author-cafe", authorDisplayName: "Kiezio Nachbar", spaceID: MockSpaces.questions.id, text: "Kennt jemand ein gutes Cafe zum Arbeiten in der Naehe? Ruhig, gutes WLAN und nicht zu voll waere perfekt.", category: .questions, reach: .district, createdAt: now.addingTimeInterval(-900), reactions: 12, replies: [PostReply(id: UUID(), text: "Das kleine Cafe am Markt ist morgens super ruhig. Nach 15 Uhr wird es voller.", createdAt: now.addingTimeInterval(-420), reactions: 5, authorTrust: 0.86, hasCurrentUserReacted: false)], qualityScore: 0.84, authorTrust: 0.78, reportCount: 0, moderationStatus: .visible, removalReason: nil, hasCurrentUserReacted: false),
            KiezioPost(id: UUID(), authorID: "author-events", authorDisplayName: "Event Scout", spaceID: MockSpaces.events.id, text: "Heute Abend kleiner Flohmarkt im Kiez, ab 18 Uhr im Innenhof bei der alten Druckerei.", category: .events, reach: .kiezio, createdAt: now.addingTimeInterval(-2600), reactions: 21, replies: [], qualityScore: 0.79, authorTrust: 0.81, reportCount: 0, moderationStatus: .visible, removalReason: nil, hasCurrentUserReacted: false),
            KiezioPost(id: UUID(), authorID: "author-bike", authorDisplayName: "Werkbank", spaceID: MockSpaces.recommendations.id, text: "Hat jemand Erfahrungen mit Fahrradwerkstatt XY? Suche faire Preise fuer eine Schaltungseinstellung.", category: .recommendations, reach: .city, createdAt: now.addingTimeInterval(-5600), reactions: 8, replies: [], qualityScore: 0.68, authorTrust: 0.70, reportCount: 0, moderationStatus: .visible, removalReason: nil, hasCurrentUserReacted: false),
            KiezioPost(id: UUID(), authorID: "author-transit", authorDisplayName: "Pendlerblick", spaceID: MockSpaces.mobility.id, text: "Achtung: S-Bahn faellt teilweise aus. Zwischen Hauptbahnhof und Ostkreuz faehrt gerade Ersatzverkehr.", category: .warnings, reach: .city, createdAt: now.addingTimeInterval(-1400), reactions: 34, replies: [PostReply(id: UUID(), text: "Bus 142 ist gerade die schnellste Alternative.", createdAt: now.addingTimeInterval(-800), reactions: 9, authorTrust: 0.88, hasCurrentUserReacted: false)], qualityScore: 0.91, authorTrust: 0.83, reportCount: 0, moderationStatus: .visible, removalReason: nil, hasCurrentUserReacted: false),
            KiezioPost(id: UUID(), authorID: "author-running", authorDisplayName: "Laufgruppe", spaceID: MockSpaces.help.id, text: "Suche jemanden fuer eine lockere Laufgruppe, 5 km, eher entspannt als Leistungssport.", category: .help, reach: .district, createdAt: now.addingTimeInterval(-9200), reactions: 17, replies: [], qualityScore: 0.74, authorTrust: 0.76, reportCount: 0, moderationStatus: .visible, removalReason: nil, hasCurrentUserReacted: false),
            KiezioPost(id: UUID(), authorID: "author-humor", authorDisplayName: "Kiezmoment", spaceID: MockSpaces.area.id, text: "Der Moment, wenn man nur kurz Broetchen holen will und mit drei Nachbarschaftsnews zurueckkommt.", category: .humor, reach: .kiezio, createdAt: now.addingTimeInterval(-7200), reactions: 29, replies: [], qualityScore: 0.62, authorTrust: 0.66, reportCount: 0, moderationStatus: .visible, removalReason: nil, hasCurrentUserReacted: false)
        ]
    }
}
